wandb_version: 1

epoch:
  desc: null
  value: 7
learning_rate:
  desc: null
  value: 0.0792180639599159
img_size:
  desc: null
  value:
  - 128
  - 128
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1731562609.36939
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      - 37
      4: 3.9.7
      5: 0.16.0
      8:
      - 1
      - 5
      10:
      - 9
      13: linux-x86_64
